### ISSUE TITLE
I don't know how? Please help me

### ISSUE THREAD

**Issue by karthickrock** [LocalCoinSwap/api-examples#2]
Can you please explain how wallet addresses for  individual users generated?Do I need individual authorization tokens for all users to generate wallet address?

**Comment by ravi-ojha** [comment]
@karthickrock Each user gets a 24-word mnemonic. This is unique to each user. We store an encrypted version in the backend. When you login to our website, that encrypted mnemonic is decrypted using your credentials. 

This mnemonic is then used to generate addresses for different cryptos.
