### ISSUE TITLE
how to put ETH into Escrow using API

### ISSUE THREAD

**Issue by domalaq** [LocalCoinSwap/api-examples#3]
Hi,
couldn't find any info about that in API Docs. I've been able to create a trade and now status is `WAITING_FOR_ESCROW'.
I've seen that when I interact with UI it makes transaction to contract. but how can I do the same with API?

**Comment by sycore0** [comment]
i too would like to hear the answer to this, as i'm stuck on this part as well

**Comment by sycore0** [comment]
any update on this guys?

**Comment by ravi-ojha** [comment]
@domalak @sycore0 I have added an example walkthrough document that explains the non-custodial ETH trading process. 

Here: https://github.com/LocalCoinSwap/api-examples/blob/master/docs/2-non-custodial-eth-trade.md

Lemme know if you run into any issues.

**Comment by sycore0** [comment]
oh man thanks so much! this really helps clear things out

**Comment by domalaq** [comment]
We managed to make this. Thank you!
